### ISSUE TITLE
Update sensitivity table

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_MLX90393#19] opened 2020-10-12 19:32 UTC
This was brought up in the Arduino lib. See here for ref:
https://github.com/adafruit/Adafruit_MLX90393_Library/issues/4

**Comment by caternuson** [comment] 2020-10-15 15:39
For anyone thinking of working this issue, be sure to check the discussion here first:
https://github.com/adafruit/Adafruit_MLX90393_Library/issues/7
There is on going confusion w.r.t. to latest rev of datasheet and what values to use.

**Comment by SAK917** [comment] 2021-02-26 08:31
Hi @caternuson, I saw this issue languishing in the Good First Issue list and thought I would take a stab at it.  However, after reading the discussion in [adafruit/Adafruit_MLX90393_Library#7](https://github.com/adafruit/Adafruit_MLX90393_Library/issues/7) as instructed above, it appears to me that the values in `_LSB_LOOKUP` already match the values for `HALLCONF = 0x0C` in the table that is discussed.  I believe the issue was originally raised due to a typo in the tables and nothing actually needs to be changed, so perhaps this issue could be closed as well?  Happy to do whatever I can if I misunderstood things... just point me in the right direction.

**Comment by caternuson** [comment] 2021-02-26 16:28
I *think* this still needs to be done. The main change was from a single table to multiple tables:
https://github.com/adafruit/Adafruit_MLX90393_Library/issues/4#issuecomment-685023343
With separate values for `HALLCONF = 0x0C` and `HALLCONF = 0x00`. This library is still currently only using a table with a single set of values.

The confusion was in the new datasheets with multiple tables. There were typos that made it confusing w.r.t to `HALLCONF`. I actually emailed Melexis and they confirmed it was a typo: 

>  But to answer the question, the first table is for HallConf = 0xC and the second table is for HallConf = 0x0.

Checkout the PR over in that Arduino thread for example changes needed:
https://github.com/adafruit/Adafruit_MLX90393_Library/pull/5/files

**Comment by SAK917** [comment] 2021-02-26 17:48
Thanks for the input Carter, that makes sense.  I saw the discussion on the other PR regarding which table was correct for the different HallConf values, but didn't realize that there was a separate PR to implement using both values.  I will take a look at the Arduino library PR you point me too and see if I can reproduce the functionality in the CP version.

**Comment by SAK917** [comment] 2021-03-02 19:50
@caternuson  Just wanted to let you know I submitted a PR for this issue.  I deviated slightly from the Arduino version you pointed me to and documented the reason / rationale in the PR description.  Please let me know if you have any questions or need more information.  Thanks!

**Closed** 2021-03-02 20:46 UTC
Labels: good first issue
